"use client";
import Image from "next/image"; import {useEffect,useState} from "react"; import {ArrowRight,CalendarDays,ChevronDown,Clock3,Menu,Search,Send,ShieldCheck,Sparkles,X} from "lucide-react";
import {studentTypes} from "@/data/studentTypes"; import {contacts} from "@/data/contacts"; import {faqs} from "@/data/content"; import {getTasksForStudent} from "@/lib/tasks";
const assetPath=(path:string)=>`${process.env.NEXT_PUBLIC_BASE_PATH??""}${path}`;
export default function Home(){
 const [type,setType]=useState(()=>typeof window!=="undefined"?(localStorage.getItem("must-student-type")||"day-4year"):"day-4year"),[chat,setChat]=useState(false),[menu,setMenu]=useState(false),[question,setQuestion]=useState(""),[answer,setAnswer]=useState("選一個問題，或直接輸入你想了解的事情。"),[openFaq,setOpenFaq]=useState<number|null>(0),[showLookup,setShowLookup]=useState(false),[idNumber,setIdNumber]=useState(""),[lookupResult,setLookupResult]=useState(false);
 useEffect(()=>{localStorage.setItem("must-student-type",type)},[type]);
 const selected=studentTypes.find(s=>s.id===type)!; const all=getTasksForStudent(type); const required=all.filter(t=>t.requirement==="required"); const conditional=all.filter(t=>t.requirement!=="required");
 const ask=(q:string)=>{setQuestion("");const key=q.includes("宿舍")?"dorm":q.includes("貸款")||q.includes("繳費")?"payment":q.includes("健檢")?"health":q.includes("學號")?"student-id":null;const t=all.find(x=>x.id===key);setAnswer(t?`${t.title}：${t.description} 正式日期、辦理網址與承辦資訊目前待行政單位確認。`:`目前沒有找到明新官方確認的這項資訊。建議從下方任務或聯絡窗口繼續查找。`)};
 return <>
 <header className="header"><a className="brand" href="#top"><span className="logo">M</span><span><b>明新新鮮人</b><small>MUST FRESHMAN</small></span></a><nav className={menu?"nav open":"nav"}><a href="#journey">必辦流程</a><a href="#conditional">依情況辦理</a><a href="#services">常用服務</a><a href="#life">校園生活</a><a href="#faq">FAQ</a></nav><div className="headerActions"><button className="iconButton" aria-label="搜尋"><Search/></button><button className="menuButton" onClick={()=>setMenu(!menu)} aria-label="開啟選單">{menu?<X/>:<Menu/>}</button></div></header>
 <main id="top">
  <section className="hero"><div className="blob b1"/><div className="blob b2"/><div className="heroText"><span className="eyebrow"><Sparkles size={16}/> 115 學年度新生入口</span><h1>嗨，新鮮人！<br/><em>準備好出發了嗎？</em></h1><p>先確認身分，再照著必辦流程一步一步完成。你不需要先了解學校的行政組織。</p><div className="heroButtons"><a className="button primary" href="#journey">查看我的必辦流程 <ArrowRight/></a><a className="button ghost" href="#services">常用服務</a></div></div><div className="heroArt"><div className="sun">HELLO!</div><Image src={assetPath("/mascot/humanities.png")} alt="明新新生公仔向你打招呼" width={420} height={520} priority/><div className="sticker s1">一步一步<br/><b>不迷路！</b></div><div className="sticker s2">MUST<br/>GO!</div></div>
  <div className="selectorWrap"><div><span className="stepNo">01</span><div><b>先確認你的新生身分</b><small>選擇身分後，下一區會產生你的必辦流程</small></div></div><label><span>我是</span><select value={type} onChange={e=>setType(e.target.value)}>{studentTypes.map(s=><option value={s.id} key={s.id}>{s.label}</option>)}</select><ChevronDown/></label><button className="identityHelp" onClick={()=>{setShowLookup(!showLookup);setLookupResult(false)}}>用身分證號查詢身分</button>{showLookup&&<><button className="lookupBackdrop" type="button" aria-label="關閉新生身分查詢" onClick={()=>{setShowLookup(false);setLookupResult(false);setIdNumber("")}}/><form className="identityLookup" role="dialog" aria-modal="true" aria-labelledby="lookup-title" onSubmit={e=>{e.preventDefault();if(idNumber.trim())setLookupResult(true)}}><div className="lookupTitle"><ShieldCheck/><span><b id="lookup-title">新生身分查詢｜功能預留</b><small>未來可串接校方招生資料，查詢學生身分與入學管道</small></span><button className="lookupClose" type="button" aria-label="關閉新生身分查詢" onClick={()=>{setShowLookup(false);setLookupResult(false);setIdNumber("")}}><X/></button></div><label><span>身分證號</span><input value={idNumber} onChange={e=>setIdNumber(e.target.value.toUpperCase())} placeholder="例如 A123456789" maxLength={10} autoComplete="off"/></label><button type="submit">查詢我的身分</button><small className="lookupNotice">Prototype 不會儲存或傳送輸入內容，目前無法查詢真實資料。</small>{lookupResult&&<div className="lookupResult"><b>尚未串接招生資料庫</b><span>未來預計顯示：學生身分、入學管道，以及對應的必辦流程。</span></div>}</form></>}</div>
  </section>
  <section className="mustFlow" id="journey"><div className="flowHeading"><span className="bigStep">02</span><div><span className="kicker">REQUIRED STEPS</span><h2>照順序完成開學前必辦流程</h2><p>以下是「{selected.label}」目前設定為每位新生都要完成的項目。從第 1 步開始，就不容易漏掉。</p></div><span className="mustCount">共 {required.length} 項必辦</span></div>{required.length?<div className="flowList">{required.map((t,i)=><article className="flowCard" key={t.id}><div className="flowNumber"><small>STEP</small><b>{String(i+1).padStart(2,"0")}</b></div><div className="flowIcon">{["🔎","🔐","📝","💳","📚","❤️","🎒","🎉"][i]||"✓"}</div><div className="flowCopy"><span className="requiredLabel">必須完成</span><h3>{t.title}</h3><p>{t.description}</p><div className="flowMeta"><span><Clock3/> 辦理日期：待行政單位確認</span>{i>0&&<span>請先完成第 {i} 步</span>}</div></div><a href="#contact">前往辦理 <ArrowRight/></a>{i<required.length-1&&<div className="flowArrow">↓</div>}</article>)}</div>:<div className="emptyFlow">此身分沒有設定共同必辦流程，請查看下方相關資訊。</div>}</section>
  <section className="section conditionalSection" id="conditional"><div className="sectionHead"><div><span className="kicker">CHECK YOUR NEEDS</span><h2>再確認：這些要依你的情況辦理</h2><p>不是每位新生都需要完成。符合需求或資格時，再點進去確認。</p></div></div><div className="conditionalGrid">{conditional.map((t,i)=><article key={t.id}><span className="conditionIcon">{["🤝","🏠","📄","🚌"][i]||"✓"}</span><div><span className="conditionalLabel">依個人情況</span><h3>{t.title}</h3><p>{t.id==="dorm"?"有住宿需求的新生才需要辦理。":t.id==="aid"?"需要減免或就學貸款的同學才需要辦理。":t.description}</p></div><a href="#contact">了解是否需要 <ArrowRight/></a></article>)}</div></section>
  <section className="services" id="services"><div className="sectionHead"><div><span className="kicker">QUICK ACCESS</span><h2>常用服務，一鍵抵達</h2><p>正式網址確認後，每個入口都會直接連到對應的官方頁面。</p></div></div><div className="serviceGrid"><a href="#contact" className="calendarService"><span><CalendarDays/></span><div><b>新生行事曆</b><small>查看重要日期與截止時間</small></div><ArrowRight/></a>{all.slice(0,7).map((t,i)=><a href="#contact" key={t.id}><span>{["🔍","🔑","📋","💰","🤝","🏠","📚"][i]}</span><div><b>{t.shortTitle}</b><small>{t.category}</small></div><ArrowRight/></a>)}</div></section>
  <section className="life" id="life"><div className="lifeIntro"><span className="kicker">CAMPUS LIFE</span><h2>不只辦手續，<br/>也開始認識明新</h2><p>校園探索、學習資源與生活情報，都替你放在一起。</p><a href="#services">探索校園生活 <ArrowRight/></a></div><div className="mascotLine">{[["engineering.png","工程藍","校園地圖"],["semiconductor.png","科技綠","學習資源"],["human-ecology.png","生活粉","餐飲生活"],["management.png","活力橘","社團活動"]].map(x=><div key={x[0]}><Image src={assetPath(`/mascot/${x[0]}`)} alt={`${x[1]}明新公仔`} width={150} height={180}/><b>{x[2]}</b><small>{x[1]}</small></div>)}</div></section>
  <section className="section faqSection" id="faq"><div className="faqIntro"><span className="kicker">FRESHMAN FAQ</span><h2>新生常見問題</h2><p>先整理新生與家長最可能提出的問題，供行政單位在會議中確認答案與資料負責單位。</p><Image src={assetPath("/mascot/engineering.png")} alt="明新公仔協助解答問題" width={180} height={210}/></div><div className="faq">{faqs.map((f,i)=><div key={i}><button onClick={()=>setOpenFaq(openFaq===i?null:i)} aria-expanded={openFaq===i}><b><span>Q{String(i+1).padStart(2,"0")}</span>{f[0]}</b><span>{openFaq===i?"−":"+"}</span></button>{openFaq===i&&<p>{f[1]}</p>}</div>)}</div></section>
  <section className="contact" id="contact"><div><span>還有問題？</span><h2>別擔心，我們陪你找到答案。</h2><p>Prototype 階段尚未填入正式聯絡資料；確認後可直接由資料檔更新，不需修改介面。</p></div><div><b>{contacts[0].department}</b><span>承辦人：{contacts[0].name}</span><span>電話：{contacts[0].phone}</span><span>Email：{contacts[0].email}</span></div></section>
 </main>
 <footer><div className="brand"><span className="logo">M</span><span><b>明新科技大學</b><small>明新新生智慧導航平台</small></span></div><p>地址、總機與網站聯絡單位：待行政單位確認</p><small>© MUST Smart Freshman Navigator · Prototype</small></footer>
 <button className="aiButton" onClick={()=>setChat(true)} aria-label="開啟 AI 新生小幫手"><Image src={assetPath("/mascot/semiconductor.png")} alt="" width={62} height={68}/><span>有問題？<b>問我就好！</b></span></button>
 {chat&&<aside className="chat" aria-label="AI 新生小幫手"><header><div><span>AI</span><div><b>明新新生小幫手</b><small>目前身分：{selected.label}</small></div></div><button onClick={()=>setChat(false)} aria-label="關閉"><X/></button></header><div className="messages"><div className="bot">👋 嗨！不知道接下來要做什麼嗎？我會依網站的 Mock Data 協助你找方向。</div><div className="bot answer">{answer}</div><div className="prompts">{["我現在要做什麼？","如何查學號？","學費怎麼繳？","我要申請宿舍","轉學生需要健檢嗎？"].map(q=><button onClick={()=>ask(q)} key={q}>{q}</button>)}</div></div><form onSubmit={e=>{e.preventDefault();if(question.trim())ask(question)}}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="輸入你的問題…" aria-label="輸入問題"/><button aria-label="送出"><Send/></button></form><small className="privacy">請勿輸入密碼、身分證字號或其他敏感個人資料。</small></aside>}
 </>;
}
